### ISSUE TITLE
TypeError: imagesResponse.data.match is not a function

### ISSUE THREAD

**Issue by fenchai23** [nociza/Bimg#1]
this is while using generateImagesLinks(), I noticed it happens when my prompt is larger than a few characters.

with more testing it seems its random, no matter the prompt size. now I really have no idea what is going on.

**Comment by nociza** [comment]
Hi, can you give some examples of prompts that induce this behavior? I'm trying to reproduce the bug

**Comment by fenchai23** [comment]
> Hi, can you give some examples of prompts that induce this behavior? I'm trying to reproduce the bug

ok I think I might know why it produces this error.

I tested just now:

- beautiful city at night with lots of lights 4k  and cats watching the landscape (works)
- superman eating noodles in a library at night and many people are watching him (works)
- adam and eve looking at the sun in the vast field (works)
- trump holding a cat with sunglases and in front the USA flag (error)

I think theres some kind of safety system that blocks any kind of controversial or sensitive prompts like (presidents, countries, flags, homosexuality, etc)

**Comment by nociza** [comment]
You're right, the error is from Bing rejecting the prompt due to content violation. I don't think there's a way to by-pass that right now, but I added some better error handling to throw a more useful error when this happens.
