### ISSUE TITLE
Change dead Chrome extension link

### ISSUE THREAD

**Issue by NotFenixio** [nociza/Bimg#5]
Hi there!

The link for the [Chrome extension](https://chrome.google.com/webstore/detail/get-cookiestxt-locally/) in README.md returns a 404 error.
This is the correct link: [https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc](https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc)

Best regards!

**Comment by nociza** [comment]
Thanks for catching the bug! Fixed.
